# Generated by Django 5.1.2 on 2024-11-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_alter_ride_driver'),
    ]

    operations = [
    ]
