# Generated by Django 5.1.2 on 2024-11-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_ride_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='available_seats',
            field=models.IntegerField(),
        ),
    ]
